### ISSUE TITLE
In mobile looks like the camera has a rotation = -90;

### ISSUE THREAD

**Issue by fukhaos** [shin10/Starling-WebcamVideo#1]
In mobile looks like the camera has a rotation = -90,
in webcam show correct.

My app is portrait.

**Comment by shin10** [comment]
Hi fukhaos :D

Actually that's pretty normal. That's because of the physical rotation of the camera's sensor, which is build into the device in landscape-aspect orientation.

The flash reference (http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/Camera.html) states:
"A Camera instance captures video in landscape aspect ratio. On devices that can change the screen orientation, such as mobile phones, a Video object attached to the camera will only show upright video in a landscape-aspect orientation. Thus, mobile apps should use a landscape orientation when displaying video and should not auto-rotate.

On iOS, the video from the front camera is mirrored. On Android, it is not."

I could have handled this more or less, but I thought it might lead to much more confusion than comfort.
Besides Adobes recommondation the following things are possible:
- If StageOrientation is DEFAULT or UPSIDE_DOWN, change the rotation of the display object with webcamVideo.rotation = 90; 
- or internally within the class by changing the vertices.

Both options would show the image in correct orientation, BUT obviously with switched width/height and therefore only an option for square images unless you also change the camera's resolution.
Furthermore the data (bitmapData/byteArray and texture) will still be oriented just as you see it now.
- internally use of bitmapData.draw() with a matrix to "correct" data and appearance, which is only possible in one of the draw/upload-strategies and therefore I didn't consider it as a good option.
- last but not least you could switch off auto-rotate and create a landscape only app like suggested by Adobe, and rotate the starling stage instead. But I guess that's leading to even more problems ... I definitely should try that :)

Well, I hope that sheds some light on that subject. Which way works best depends on what you're building.
However it's not a bug.
